<?php

namespace Database\Seeders;

use App\Models\Sdg;
use Illuminate\Database\Seeder;

class SdgSeeder extends Seeder
{
    public function run(): void
    {
        $sdgs = [
            1 => ['title' => 'No Poverty', 'image' => 'sdg1.png', 'description' => 'End poverty in all its forms everywhere', 'importance' => 'Poverty is one of the most pressing issues of our time, affecting billions of people worldwide.', 'target1' => 'By 2030, eradicate extreme poverty for all people everywhere', 'target2' => 'By 2030, reduce at least by half the proportion of men, women and children of all ages living in poverty in all its dimensions according to national definitions', 'target3' => 'Ensure equal rights to economic resources as well as access to basic services, ownership and control over land and other forms of property, inheritance, natural resources, appropriate new technology and financial services, including microfinance', 'action1' => 'Support local businesses and fair trade products', 'action2' => 'Donate to reputable charities working to alleviate poverty', 'action3' => 'Advocate for policies that promote economic equality and social protection'],
            2 => ['title' => 'Zero Hunger', 'image' => 'sdg2.png', 'description' => 'End hunger, achieve food security and improved nutrition', 'importance' => 'Hunger and malnutrition are major global challenges that affect millions of people, particularly children.', 'target1' => 'By 2030, end hunger and ensure access by all people to safe, nutritious and sufficient food all year round', 'target2' => 'By 2030, end all forms of malnutrition, including achieving targets on stunting and wasting in children under 5', 'target3' => 'By 2030, double the agricultural productivity and incomes of small-scale food producers', 'action1' => 'Reduce food waste by planning meals and composting organic waste', 'action2' => 'Support local farmers and community gardens', 'action3' => 'Donate to food banks and programs fighting hunger'],
            3 => ['title' => 'Good Health', 'image' => 'sdg3.png', 'description' => 'Ensure healthy lives and promote well-being for all at all ages', 'importance' => 'Good health is a fundamental human right and a key driver of development.', 'target1' => 'By 2030, reduce the global maternal mortality ratio to less than 70 per 100,000 live births', 'target2' => 'By 2030, end the epidemics of AIDS, tuberculosis, malaria and neglected tropical diseases', 'target3' => 'By 2030, reduce premature mortality from non-communicable diseases through prevention and treatment', 'action1' => 'Exercise regularly and maintain a balanced diet', 'action2' => 'Get vaccinated and attend regular health check-ups', 'action3' => 'Support mental health awareness and reduce stigma'],
            4 => ['title' => 'Quality Education', 'image' => 'sdg4.png', 'description' => 'Ensure inclusive and equitable quality education and promote lifelong learning opportunities for all', 'importance' => 'Education is a fundamental human right and a key driver of development.', 'target1' => 'By 2030, ensure all girls and boys complete free, equitable and quality primary and secondary education', 'target2' => 'By 2030, ensure equal access for all to affordable and quality technical and vocational education', 'target3' => 'By 2030, eliminate gender disparities in education and ensure equal access to all levels of education', 'action1' => 'Read books and share knowledge with others', 'action2' => 'Support educational charities and mentorship programs', 'action3' => 'Advocate for equal access to education for all children'],
            5 => ['title' => 'Gender Equality', 'image' => 'sdg5.png', 'description' => 'Achieve gender equality and empower all women and girls', 'importance' => 'Gender equality is a fundamental human right and a key driver of development.', 'target1' => 'End all forms of discrimination against all women and girls everywhere', 'target2' => 'Eliminate all forms of violence against women and girls, including trafficking and exploitation', 'target3' => 'Ensure womens full and effective participation and equal opportunities for leadership at all levels', 'action1' => 'Speak up against gender stereotypes and bias', 'action2' => 'Support women-led businesses and organizations', 'action3' => 'Advocate for equal pay and parental leave policies'],
            6 => ['title' => 'Clean Water', 'image' => 'sdg6.png', 'description' => 'Ensure availability and sustainable management of water and sanitation for all', 'importance' => 'Access to clean water is a fundamental human right and a key driver of development.', 'target1' => 'Achieve universal and equitable access to safe and affordable drinking water for all', 'target2' => 'Achieve access to adequate and equitable sanitation and hygiene for all, ending open defecation', 'target3' => 'Improve water quality by reducing pollution, eliminating dumping, and minimizing hazardous chemicals', 'action1' => 'Turn off the tap while brushing your teeth', 'action2' => 'Collect rainwater for gardening and cleaning', 'action3' => 'Avoid dumping chemicals or waste into water sources'],
            7 => ['title' => 'Clean Energy', 'image' => 'sdg7.png', 'description' => 'Ensure access to affordable, reliable, sustainable and modern energy for all', 'importance' => 'Access to clean energy is a fundamental human right and a key driver of development.', 'target1' => 'Ensure universal access to affordable, reliable and modern energy services by 2030', 'target2' => 'Increase substantially the share of renewable energy in the global energy mix', 'target3' => 'Double the global rate of improvement in energy efficiency by 2030', 'action1' => 'Switch to LED light bulbs and energy-efficient appliances', 'action2' => 'Unplug electronics when not in use to save energy', 'action3' => 'Support or invest in renewable energy projects'],
            8 => ['title' => 'Decent Work', 'image' => 'sdg8.png', 'description' => 'Promote sustained, inclusive economic growth, full and productive employment and decent work for all', 'importance' => 'Decent work is a fundamental human right and a key driver of development.', 'target1' => 'Achieve full and productive employment and decent work for all women and men by 2030', 'target2' => 'Eradicate forced labor, modern slavery, and human trafficking by 2030', 'target3' => 'End child labor in all its forms by 2025', 'action1' => 'Support fair trade products and ethical businesses', 'action2' => 'Advocate for fair wages and safe working conditions', 'action3' => 'Invest in skills development and lifelong learning'],
            9 => ['title' => 'Industry & Innovation', 'image' => 'sdg9.png', 'description' => 'Build resilient infrastructure, promote inclusive and sustainable industrialization and foster innovation', 'importance' => 'Industry and innovation are key drivers of economic growth and development.', 'target1' => 'Develop quality, reliable, sustainable and resilient infrastructure to support economic development', 'target2' => 'Promote inclusive and sustainable industrialization by increasing industry employment and GDP share', 'target3' => 'Enhance scientific research and upgrade technological capabilities in all countries', 'action1' => 'Learn coding, robotics, or other tech skills', 'action2' => 'Support innovative startups and local inventors', 'action3' => 'Advocate for investment in research and development'],
            10 => ['title' => 'Reduced Inequalities', 'image' => 'sdg10.png', 'description' => 'Reduce inequality within and among countries', 'importance' => 'Reducing inequality is essential for sustainable development and social cohesion.', 'target1' => 'Empower and promote the social, economic and political inclusion of all, regardless of age, sex, disability, race, or ethnicity', 'target2' => 'Ensure equal opportunity and reduce inequalities of outcome, including through eliminating discriminatory laws', 'target3' => 'Adopt fiscal, wage, and social protection policies to achieve greater equality', 'action1' => 'Listen to and amplify marginalized voices', 'action2' => 'Support organizations that fight discrimination', 'action3' => 'Advocate for inclusive policies in your community'],
            11 => ['title' => 'Sustainable Cities', 'image' => 'sdg11.png', 'description' => 'Make cities and human settlements inclusive, safe, resilient and sustainable', 'importance' => 'Urbanization is a key driver of economic growth and development.', 'target1' => 'Ensure access for all to adequate, safe and affordable housing and basic services by 2030', 'target2' => 'Provide access to safe, affordable, accessible and sustainable transport systems for all', 'target3' => 'Reduce the environmental impact of cities by focusing on air quality and waste management', 'action1' => 'Use public transportation, bike, or walk whenever possible', 'action2' => 'Participate in community clean-up and greening projects', 'action3' => 'Support urban planning that prioritizes green spaces'],
            12 => ['title' => 'Responsible Consumption', 'image' => 'sdg12.png', 'description' => 'Ensure sustainable consumption and production patterns', 'importance' => 'Sustainable consumption and production are essential for environmental protection and social well-being.', 'target1' => 'Achieve the sustainable management and efficient use of natural resources by 2030', 'target2' => 'Halve per capita global food waste at the retail and consumer levels by 2030', 'target3' => 'Achieve environmentally sound management of chemicals and all wastes throughout their life cycle', 'action1' => 'Reduce, reuse, and recycle — buy only what you need', 'action2' => 'Choose products with minimal packaging and eco-friendly materials', 'action3' => 'Compost food scraps and avoid single-use plastics'],
            13 => ['title' => 'Climate Action', 'image' => 'sdg13.jpg', 'description' => 'Take urgent action to combat climate change and its impacts', 'importance' => 'Climate change is one of the most significant challenges of our time.', 'target1' => 'Strengthen resilience and adaptive capacity to climate-related hazards and natural disasters', 'target2' => 'Integrate climate change measures into national policies, strategies, and planning', 'target3' => 'Improve education and awareness on climate change mitigation, adaptation, and impact reduction', 'action1' => 'Plant trees and support reforestation projects', 'action2' => 'Reduce your carbon footprint by using renewable energy and reducing travel emissions', 'action3' => 'Educate others about climate change and advocate for climate policies'],
            14 => ['title' => 'Life Below Water', 'image' => 'sdg14.png', 'description' => 'Conserve and sustainably use the oceans, seas and marine resources', 'importance' => 'Oceans are vital for life on Earth and support the livelihoods of millions of people.', 'target1' => 'Prevent and significantly reduce marine pollution of all kinds by 2025', 'target2' => 'Sustainably manage and protect marine and coastal ecosystems to avoid significant impacts', 'target3' => 'Minimize and address the impacts of ocean acidification through scientific cooperation', 'action1' => 'Say no to single-use plastics that end up in the ocean', 'action2' => 'Choose sustainable seafood and avoid overfished species', 'action3' => 'Participate in beach clean-ups and coastal conservation'],
            15 => ['title' => 'Life On Land', 'image' => 'sdg15.png', 'description' => 'Protect, restore and promote sustainable use of terrestrial ecosystems', 'importance' => 'Terrestrial ecosystems are crucial for biodiversity, food security, and climate regulation.', 'target1' => 'Ensure the conservation, restoration and sustainable use of terrestrial and freshwater ecosystems', 'target2' => 'Promote sustainable forest management, halt deforestation, and restore degraded forests', 'target3' => 'Take urgent action to end poaching and trafficking of protected species of flora and fauna', 'action1' => 'Plant native trees and create wildlife-friendly gardens', 'action2' => 'Avoid products that harm forests or endangered species', 'action3' => 'Support national parks and wildlife conservation efforts'],
            16 => ['title' => 'Peace & Justice', 'image' => 'sdg16.png', 'description' => 'Promote peaceful and inclusive societies for sustainable development', 'importance' => 'Peace and justice are fundamental to human development and well-being.', 'target1' => 'Significantly reduce all forms of violence and related death rates everywhere', 'target2' => 'Promote the rule of law and ensure equal access to justice for all', 'target3' => 'Develop effective, accountable and transparent institutions at all levels', 'action1' => 'Stand up against injustice and report corruption', 'action2' => 'Participate in community dialogue and conflict resolution', 'action3' => 'Support organizations promoting human rights and legal aid'],
            17 => ['title' => 'Partnerships', 'image' => 'sdg17.png', 'description' => 'Strengthen the means of implementation and revitalize the global partnership for sustainable development', 'importance' => 'Global partnerships are essential for achieving the Sustainable Development Goals.', 'target1' => 'Strengthen domestic resource mobilization to improve capacity for tax and revenue collection', 'target2' => 'Promote a universal, rules-based, open and equitable multilateral trading system', 'target3' => 'Enhance international support for capacity-building in developing countries', 'action1' => 'Collaborate with people from different cultures and backgrounds', 'action2' => 'Support international development organizations and fair trade', 'action3' => 'Advocate for global cooperation on shared challenges'],
        ];

        foreach ($sdgs as $sdg) {
            Sdg::create($sdg);
        }
    }
}
